### PR TITLE
Remove mayavi dependency and build with newer numpy

### LINKED ISSUE #1: New build with newer numpy
@leouieda now that we got a [version](http://anaconda.org/conda-forge/fatiando/files) with `numpy 1.9` and `mayavi` you can, if you think it is useful, issue a new build number by removing `mayavi` and switching `numpy 1.9.*` to `numpy x.x`.

That would give people who do not want `mayavi` to install `fatiando` with a newer `numpy` while still leaving a restricted `numpy 1.9`+`mayavi` version on the channel for those who need it.

### PR DESCRIPTION
**Pull request by leouieda**
Fixes #1 

Will use the `no-mayavi` branch to build versions of Fatiando with newer numpy that don't depend on Mayavi.

### CODE REVIEW

**Comment by jakirkham** [comment]
Changing to `numpy x.x` requires a re-rendering. Please do the following.
- `conda install -y -n root conda-smithy`
- `cd <some feedstock>`
- `conda smithy rerender`
- Commit all changes and push.

**Comment by leouieda** [comment]
@jakirkham done! Thanks

**Comment by jakirkham** [comment]
LGTM.

**Comment by ocefpaf** [comment]
@leouieda PRs in the feedstock are, most of the time, fair game to self-merge. When you do need someone to take a look feel free to ping me. (Or invite more maintainers for fatiando-feedstock :grimacing:)

**Comment by leouieda** [comment]
@ocefpaf I'm sure I'll have some more doubts in the future :smiley: 

I'm trying to coerce some people to join as maintainers but I'm afraid of scaring off my few contributors with tons of work.

**Comment by ocefpaf** [comment]
> I'm afraid of scaring off my few contributors with tons of work.

That happens. BTW we just updated the README in staged recipes with [this](https://github.com/conda-forge/staged-recipes#10-what-does-being-a-conda-forge-feedstock-maintainer-entail). That may be useful when inviting collaborators.

**Comment by leouieda** [comment]
Nice additions. I'll definitely link to that.

**Pull request merged**
