### PR TITLE
Update to v0.5 with Mayavi as dependency

### PR DESCRIPTION
**Pull request by leouieda**

### CODE REVIEW

**Comment by leouieda** [comment]
@ocefpaf I'm getting some weird errors in the OSX and Windows builds. They seem
to be related the Miniconda download.

In Travis, the `curl` download is failing:

    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

    /Users/travis/build.sh: line 63: conda: command not found

    /Users/travis/build.sh: line 64: conda: command not found

    /Users/travis/build.sh: line 65: conda: command not found

    /Users/travis/build.sh: line 66: run_conda_forge_build_setup: No such file or
    directory

I tried running it on my machine and it does fail. But it's not a problem with
the url because `wget` with the same argument works fine.

On Windows, the error is even stranger:

    Activating environment "C:\conda"...
    The input line is too long.
     "PATH_NO_SCRIPTS=C:\conda;;C:\conda\Library\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
    Files\7-Zip;C:\Program Files\Microsoft\Web Platform
    Installer\;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git
    LFS;C:\Program Files\Mercurial\;C:\Program Files
    (x86)\Subversion\bin;C:\Program Files\Microsoft SQL
    Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client
    SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
    Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL
    Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
    Server\120\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft Windows
    Performance Toolkit\;C:\Program Files (x86)\Windows Kits\8.1\Windows
    Performance Toolkit\;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft
    SDKs\TypeScript\1.4\;C:\Program Files (x86)\Microsoft Visual Studio
    12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft
    SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program
    Files (x86)\CMake\bin;C:\go\bin;C:\Program
    Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\erl7.3\bin;C:\Program
    Files\nodejs;C:\Program Files (x86)\iojs;C:\Program
    Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL
    Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows
    Performance Toolkit\;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files
    (x86)\Microsoft Visual Studio
    14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\120;C:\Tools\NuGet;C:\Program
    Files (x86)\Microsoft Visual Studio
    14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program
    Files\Amazon\AWSCLI\;C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\TShell\TShell\;C:\Program
    Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client
    SDK\ODBC\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program
    Files\Git\usr\bin;C:\Program Files (x86)\Microsoft SQL
    Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
    Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL
    Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
    Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
    Server\120\DTS\Binn\;C:\Program Files (x86)\Apache\Maven\bin;C:\Program
    Files\LLVM\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft Service
    Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service
    Fabric\Tools\ServiceFabricLocalClusterManager;C:\Python27\Scripts;C:\Program
    Files (x86)\Yarn\bin;C:\Program Files (x86)\nodejs\;C:\Tools\NUnit3;C:\Program
    Files\dotnet\;C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin;C:\Users\appveyor\AppData\Local\Yarn\.bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program
    Files\AppVeyor\BuildAgent\" was unexpected at this time.
    Command exited with code 255

No idea what's going on there.

I tried rerendering the recipe with conda smithy but it didn't change anything.

Any ideas?

**Comment by leouieda** [comment]
@ocefpaf sorry, it seems to be going now. I was using an outdated version of conda-smithy. Sorry about that.

**Comment by ocefpaf** [comment]
Sorry I was too slow  (or you were too fast  :-)

But you are correct. Rerendering with latest conda-smithy should fix it.

**Comment by leouieda** [comment]
@ocefpaf OK, I removed it because PyPI was complaining but conda doesn't seem to mind. I'll revert that.

**Comment by ocefpaf** [comment]
It sucks that PyPI encourage bad practices. There are 3 variants to the BSD
license and no one can figure that out using the classifiers :-(

In the conda recipe we encourage the OSI short version for the licenses,
and that includes the version in all cases.

**Comment by leouieda** [comment]
@ocefpaf right after I posted the comment I remembered that I hadn't updated. But thanks for being so responsive all the time! I have no idea how you and the other conda-forge maintainers have time for all this.

**Comment by leouieda** [comment]
@ocefpaf for some reason when I merged this to master Travis and CircleCI only triggered builds for Python 3.5 not 2.7. The Appveyor build was successful and merging #5 into the `no-mayavi` branch went off perfectly as well. I noticed because the np1.9 builds for Linux and OSX are missing from https://anaconda.org/conda-forge/fatiando/files?version=0.5

Any ideas?

**Comment by ocefpaf** [comment]
Leonardo, I am traveling am TIM just put me on the reduced speed b/c I used
all my data :-(

I will take a look as soon as I get a better connection. But check if
conda-smithy changed the build matrix when you rerendered. (There is a bug
that do that sometimes.)

**Comment by leouieda** [comment]
> TIM just put me on the reduced speed b/c I used all my data

I know exactly how you feel.

> I will take a look as soon as I get a better connection. But check if conda-smithy changed the build matrix when you rerendered. (There is a bug that do that sometimes.)

Will do. Thanks!

**Comment by leouieda** [comment]
@ocefpaf thanks, that worked!

**Pull request merged**
